### ISSUE TITLE
New release for new intellji version

### ISSUE THREAD

**Issue by cornerman** [mutcianm/intellij-external-laf-switch#2]
I just realized that this plugin is `not compatible with the version of your running IDE (IntelliJ IDEA 2023.3.1)`. Would you mind making a new release? Please let me know if I can help with anything.

**Comment by cornerman** [comment]
In the meantime, you can get a compatible plugin jar here: https://github.com/cornerman/intellij-external-laf-switch/releases/tag/2023.1

**Comment by mutcianm** [comment]
Hi! Thanks for your fix, I'll take a look after coming back from vacation on monday

**Comment by WhiteHatTux** [comment]
@mutcianm So for this to be available you will probably release a new version to the official plugin center right? Do you have a timeline for that?

**Comment by mutcianm** [comment]
@WhiteHatTux sorry again for the delay, the new build has been published

**Comment by WhiteHatTux** [comment]
thanks @mutcianm :-) Everything working flawlessly now. 👍🏽
